CREATE DATABASE IF NOT EXISTS HireUs_db;
USE HireUs_db;
drop database HireUs_db;
CREATE TABLE `users` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `password` varchar(60) NOT NULL,
  `email` varchar(100) NOT NULL,
  `full_name` varchar(100) NOT NULL,
  `phone` varchar(20) NULL,
  `date_of_birth` date DEFAULT NULL,
  `gender` enum('male','female','other') DEFAULT NULL,
  `image` varchar(100),
  `role` enum('recruiter','applicant', 'admin') NOT NULL,
  `verification_code` VARCHAR(4) NULL,
  `sent_at` TIMESTAMP NULL,
  `is_verified` BOOLEAN NOT NULL DEFAULT FALSE
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `email` (`email`)
);

CREATE TABLE `Job_positions` (
  `position_id` int(11) NOT NULL AUTO_INCREMENT,
  `position_name` varchar(50) NOT NULL,
  PRIMARY KEY (`position_id`),
  UNIQUE KEY `position_name` (`position_name`)
);


CREATE TABLE `job_types` (
  `job_type_id` int(11) NOT NULL AUTO_INCREMENT,
  `job_type_name` enum('Fulltime','Parttime','Remote','Internship','Contract') NOT NULL DEFAULT 'Fulltime',
  PRIMARY KEY (`job_type_id`)
);

CREATE TABLE `levels` (
  `level_id` int(11) NOT NULL AUTO_INCREMENT,
  `level_name` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`level_id`)
);

CREATE TABLE `companies` (
  `company_id` int(11) NOT NULL AUTO_INCREMENT,
  `company_name` varchar(100) NOT NULL,
  `logo` varchar(255) DEFAULT NULL,
  `company_website` varchar(255) DEFAULT NULL,
  `company_address` varchar(255) DEFAULT NULL,
  `employee_count` int(11) DEFAULT NULL,
  `comp_benefit` text NOT NULL,
  `founded_date` date DEFAULT NULL,
  `description` text DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`company_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `companies_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE
);

CREATE TABLE `jobs` (
  `job_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `company_id` int(11) NOT NULL,
  `job_title` varchar(100) NOT NULL,
  `job_type_id` int(11) NOT NULL,
  `status` enum('open','close') NOT NULL,
  `level_id` int(11) NOT NULL,
  `location` varchar(100) DEFAULT NULL,
  `salary` decimal(10,2) DEFAULT NULL,
  `posted_date` datetime DEFAULT current_timestamp(),
  `deadline` date NOT NULL,
  `required_candidates` int(11) NOT NULL DEFAULT 1,
  `total_applied` int(11) NOT NULL DEFAULT 0,
  `position_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`job_id`),
  KEY `user_id` (`user_id`),
  KEY `level_id` (`level_id`),
  KEY `job_type_id` (`job_type_id`),
  CONSTRAINT `jobs_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE,
  CONSTRAINT `jobs_ibfk_2` FOREIGN KEY (`company_id`) REFERENCES `companies` (`company_id`) ON DELETE CASCADE,
  CONSTRAINT `jobs_ibfk_3` FOREIGN KEY (`level_id`) REFERENCES `levels` (`level_id`) ON DELETE CASCADE,
  CONSTRAINT `jobs_ibfk_4` FOREIGN KEY (`job_type_id`) REFERENCES `job_types` (`job_type_id`) ON DELETE CASCADE,
  CONSTRAINT `jobs_ibfk_5` FOREIGN KEY (`position_id`) REFERENCES `Job_position` (`position_id`) ON DELETE CASCADE,
  CONSTRAINT `chk_required_candidates` CHECK (`required_candidates` >= 0),
  CONSTRAINT `chk_total_applied` CHECK (`total_applied` >= 0)
);

CREATE TABLE `job_responsibilities` (
  `responsibility_id` int(11) NOT NULL AUTO_INCREMENT,
  `job_id` int(11) NOT NULL,
  `responsibility` text NOT NULL,
  PRIMARY KEY (`responsibility_id`),
  KEY `job_id` (`job_id`),
  CONSTRAINT `job_responsibilities_ibfk_1` FOREIGN KEY (`job_id`) REFERENCES `jobs` (`job_id`) ON DELETE CASCADE
);

CREATE TABLE `job_requirements` (
  `requirement_id` int(11) NOT NULL AUTO_INCREMENT,
  `job_id` int(11) NOT NULL,
  `requirement` text NOT NULL,
  PRIMARY KEY (`requirement_id`),
  KEY `job_id` (`job_id`),
  CONSTRAINT `job_requirements_ibfk_1` FOREIGN KEY (`job_id`) REFERENCES `jobs` (`job_id`) ON DELETE CASCADE
);

CREATE TABLE `job_benefits` (
  `benefit_id` int(11) NOT NULL AUTO_INCREMENT,
  `job_id` int(11) NOT NULL,
  `benefit` text NOT NULL,
  PRIMARY KEY (`benefit_id`),
  KEY `job_id` (`job_id`),
  CONSTRAINT `job_benefits_ibfk_1` FOREIGN KEY (`job_id`) REFERENCES `jobs` (`job_id`) ON DELETE CASCADE
);


CREATE TABLE `applications` (
  `application_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `job_id` int(11) NOT NULL,
  `apply_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` enum('pending','accepted','rejected') DEFAULT 'pending',
  `cv` varchar(100) NOT NULL,
  PRIMARY KEY (`application_id`)
);

CREATE TABLE `comments` (
  `comment_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `job_id` int(11),
  `company_id` int(11),
  `comment_content` text NOT NULL,
  `rating` TINYINT(1) NOT NULL CHECK (`rating` BETWEEN 1 AND 5),
  PRIMARY KEY (`comment_id`)
);

-- Đây chỉ là data mẫu của bảng user để chạy databse thôi nha.sau này sẽ sửa lại là các toài khoản mà họ đăng ký á. 
INSERT INTO `users` (`password`, `email`, `full_name`, `phone`, `date_of_birth`, `gender`, `image`, `role`) VALUES
('hashed_password1', 'recruiter1@example.com', 'Nguyễn Văn A', '0987654321', '1985-06-15', 'male', 'avatar1.jpg', 'recruiter'),
('hashed_password2', 'recruiter2@example.com', 'Trần Thị B', '0978543210', '1990-09-22', 'female', 'avatar2.jpg', 'recruiter'),
('hashed_password3', 'recruiter3@example.com', 'Lê Minh C', '0965123784', '1987-02-11', 'male', 'avatar3.jpg', 'recruiter'),
('hashed_password4', 'recruiter4@example.com', 'Phạm Văn D', '0954678231', '1993-11-30', 'male', 'avatar4.jpg', 'recruiter'),
('hashed_password5', 'recruiter5@example.com', 'Hoàng Mỹ E', '0945896712', '1982-07-19', 'female', 'avatar5.jpg', 'recruiter'),
('hashed_password6', 'recruiter6@example.com', 'Đỗ Quang F', '0932145879', '1989-04-25', 'male', 'avatar6.jpg', 'recruiter');


INSERT INTO Job_position (position_name)
VALUES ('Full Stack'),
	('Front End'),
    ('Back End'),
    ('Business Analyst'),
    ('Manual Tester'),
    ('Automation Tester'),
    ('DevOps'),
    ('Data Engineer'),
    ('Scrum Master'),
    ('Mobile Developer'),
    ('Game Developer'),
    ('Security Analyst'),
    ('System Administrator'),
    ('Data Scientist'),
    ('Performance Tester'),
    ('UI/UX Designer'),
    ('Cloud Engineer');

INSERT INTO `job_types` (job_type_name)  
VALUES  
    ('fulltime'),  
    ('parttime'),  
    ('remote'),  
    ('internship'),  
    ('contract');

INSERT INTO `levels` (level_name)  
VALUES  
    ('Intern'),  
    ('Fresher'),  
    ('Junior'),  
    ('Mid-Level'),  
    ('Senior'),  
    ('Lead'),  
    ('Principal'),  
    ('Architect'),  
    ('CTO');  


INSERT INTO `companies` (`company_name`, `logo`, `company_website`, `company_address`, `employee_count`, `comp_benefit`, `founded_date`, `description`, `user_id`) VALUES
('TechCorp', 'techcorp_logo.png', 'http://www.techcorp.com', '123 Tech St.', 500, 'Comprehensive health insurance, Stock options, Flexible work hours, Remote work opportunities', '2000-05-01', 'A leading technology company specializing in innovative software solutions, cloud computing, and AI-driven applications.', 1),
('HealthMed', 'healthmed_logo.png', 'http://www.healthmed.com', '456 Health Ave.', 200, 'Private health insurance, Wellness programs, Professional development courses, Flexible hours', '2010-03-15', 'A cutting-edge health technology company focused on digital healthcare solutions, medical data analytics, and AI-powered diagnostics.', 2),
('FinBank', 'finbank_logo.png', 'http://www.finbank.com', '789 Finance Rd.', 1000, 'Retirement plans, Performance-based bonuses, Hybrid work model, Learning stipends', '1995-06-20', 'A global fintech company developing secure banking software, blockchain-based financial solutions, and AI-driven risk management tools.', 3),
('EduLearn', 'edulearn_logo.png', 'http://www.edulearn.com', '101 Education Blvd.', 50, 'Work-from-home policy, Learning and development budget, Stock options, Flexible PTO', '2015-08-30', 'An EdTech platform revolutionizing online learning through AI-powered tutoring, personalized course recommendations, and VR-enhanced training.', 4),
('RetailCo', 'retailco_logo.png', 'http://www.retailco.com', '102 Retail Ln.', 300, 'Employee discounts on tech gadgets, Remote work options, Annual tech conference sponsorship, Performance bonuses', '2018-09-10', 'A technology-driven e-commerce and retail solutions company, specializing in AI-powered inventory management, digital payment systems, and smart logistics.', 5),
('KMS Technology', 'kms_logo.png', 'https://kms-technology.com', 'XLIII Specialty Coffee, 422 Đ. Ng. Thì Sĩ, Bắc Mỹ An, Ngũ Hành Sơn, Đà Nẵng', 2200, 'Full Social and Health Insurance: KMS Technology ensures full participation in social and health insurance for employees, complying with legal requirements to protect their well-being and financial security.', '2019-12-25', 'Since its establishment, KMS Đà Nẵng has achieved remarkable milestones. Within five years, the team has participated in over 40 projects across various sectors, including healthcare, finance and banking, insurance, and enterprise software.', 2 ),
('FPT Software', 'fpt_logo.png', 'https://fptsoftware.com', 'FPT Complex, 16 Ton That Thuyet, My Dinh, Nam Tu Liem, Hanoi', 20000, 'Health insurance, Advanced training programs, International job opportunities', '1999-01-13', 'Vietnam’s leading software company, providing IT services and software solutions.', 1),
('Viettel Solutions', 'viettel_logo.png', 'https://viettel.com.vn', 'Lot D26, Alley 3, Ton That Thuyet, Yen Hoa, Cau Giay, Hanoi', 50000, 'Healthcare benefits, Performance bonuses, Professional training', '2000-10-15', 'A member of Viettel Group, specializing in IT solutions and telecommunications.', 2),
('CMC Corporation', 'cmc_logo.png', 'https://www.cmc.com.vn', 'CMC Tower, Duy Tan Street, Cau Giay, Hanoi', 3000, 'Comprehensive insurance, Flexible leave policy, Creative working environment', '1993-05-26', 'A leading Vietnamese technology corporation operating in IT and telecommunications.', 3),
('VNPT Technology', 'vnpt_logo.png', 'https://vnpt.com.vn', '57 Huynh Thuc Khang, Lang Ha, Dong Da, Hanoi', 40000, 'Retirement benefits, Professional training, Family support programs', '1995-03-26', 'Vietnam Posts and Telecommunications Group, providing telecom and IT services.', 4),
('VNG Corporation', 'vng_logo.png', 'https://www.vng.com.vn', 'Z06, Street 13, Tan Thuan Dong, District 7, Ho Chi Minh City', 3000, 'Health insurance, Flexible working hours, Recreational activities', '2004-09-09', 'Vietnam’s leading technology company, known for products like Zalo and Zing.', 5),
('TMA Solutions', 'tma_logo.png', 'https://www.tma.com.vn', 'Lot 1, Street 2, Quang Trung Software Park, District 12, Ho Chi Minh City', 2500, 'Skill development training, Health insurance, Career advancement opportunities', '1997-07-20', 'A software company with extensive experience in software development and outsourcing.', 6),
('Pasona Tech Đà Nẵng', 'pasona_tech_logo.png', 'https://www.pasonatech.vn/vi', '243 Phan Đăng Lưu, Khuê Trung Ward, Cẩm Lệ District, Da Nang', 190, 'Health insurance, Professional training, International working environment', '2004-02-01', 'A 100% Japanese-owned company specializing in software development and IT services.', 1),
('Devplus', 'devplus_logo.png', 'https://devplus.edu.vn/', 'Address not available', NULL, 'Health insurance, Flexible working hours', 'Founded date not available', 'A technology company specializing in software solutions and web design.', 2),
('Kozocom', 'kozocom_logo.png', 'http://www.kozocom.com', 'Address not available', NULL, 'Health insurance, Career advancement opportunities', 'Founded date not available', 'A company providing technology solutions and software development services.', 3),
('NAB', 'nab_logo.png', 'https://www.nab.com.au', 'Address not available', NULL, 'Health insurance, Retirement plans, Flexible working hours', 'Founded date not available', 'National Australia Bank with a technology branch in Vietnam.', 4);



INSERT INTO `jobs` (`user_id`,`company_id`, `job_title`, `job_type_id`, `status`, `level_id`, `job_description`, `responsibilities`, `requirements`, `location`, `job_benefit`, `salary`, `deadline`, `required_candidates`, `total_applied`, `position_id`) 
VALUES
(1, 4, 'Senior Full Stack Developer', 1, 'open', 5, 'Develop and maintain web applications using modern technologies.', 
 'Design architecture, write clean code, conduct code reviews, and optimize performance.', 
 '5+ years of experience in full-stack development, strong knowledge of React, Node.js, and databases.', 
 'Ho Chi Minh City', 'Health insurance, stock options, remote work, learning budget', 3000.00, '2025-06-30', 2, 0, 1),

(2, 1, 'Junior Frontend Developer', 2, 'open', 3, 'Work on user interfaces and frontend development for web applications.', 
 'Develop UI components, optimize performance, and collaborate with backend engineers.', 
 '1+ year experience with React.js/Vue.js, strong understanding of HTML, CSS, JavaScript.', 
 'Hanoi', 'Flexible hours, remote work, learning stipend, annual bonuses', 1200.00, '2025-07-15', 3, 0, 2),

(3, 6, 'DevOps Engineer', 3, 'open', 4, 'Manage cloud infrastructure, CI/CD pipelines, and automation tools.', 
 'Implement CI/CD, ensure high availability, monitor cloud services.', 
 '3+ years experience in AWS/GCP, Terraform, Kubernetes, and CI/CD tools.', 
 'Da Nang', 'Paid certifications, flexible schedule, remote work option', 2500.00, '2025-06-25', 1, 0, 7),

(4, 5, 'Data Scientist', 1, 'open', 5, 'Analyze data and build predictive models for business insights.', 
 'Work with big data, create machine learning models, present findings.', 
 '4+ years experience in Python, SQL, TensorFlow, and data visualization.', 
 'Ho Chi Minh City', 'Annual bonuses, research funding, work-from-home support', 3500.00, '2025-08-10', 2, 0, 14),

(5, 9, 'Security Analyst', 5, 'open', 4, 'Ensure security best practices and monitor threats for IT systems.', 
 'Monitor security threats, perform penetration testing, and implement security policies.', 
 '3+ years in cybersecurity, knowledge of SIEM, firewalls, and ethical hacking.', 
 'Hanoi', 'Cybersecurity training, flexible work environment, team-building trips', 2800.00, '2025-07-30', 1, 0, 12), 
 
(6, 12, 'Mobile Developer (React Native)', 1, 'open', 4, 'Develop mobile applications using React Native for both iOS and Android.', 
 'Design UI components, integrate APIs, and optimize app performance.', 
 '2+ years experience with React Native, JavaScript/TypeScript, and mobile app deployment.', 
 'Ho Chi Minh City', 'Flexible hours, remote work options, stock options', 2200.00, '2025-07-10', 2, 0, 10),

(2, 8, 'Automation QA Engineer', 4, 'open', 3, 'Design and implement automated test cases for web and mobile applications.', 
 'Develop test scripts, report bugs, and collaborate with developers to ensure software quality.', 
 '1-3 years experience with Selenium, Appium, Java/Python.', 
 'Hanoi', 'Performance-based bonuses, career development programs', 2000.00, '2025-06-30', 2, 0, 6),

(3, 7, 'Backend Developer (Node.js)', 1, 'open', 4, 'Build and maintain scalable backend systems for web applications.', 
 'Develop RESTful APIs, optimize database queries, and implement security best practices.', 
 '3+ years experience with Node.js, Express, PostgreSQL/MongoDB.', 
 'Da Nang', 'Annual bonuses, work-from-home options, technical workshops', 2800.00, '2025-07-20', 3, 0, 3),

(5, 10, 'Scrum Master', 3, 'open', 5, 'Facilitate Agile ceremonies and help teams deliver high-quality software.', 
 'Lead daily standups, remove blockers, and coach teams on Agile methodologies.', 
 '3+ years experience as a Scrum Master, knowledge of Jira and Agile frameworks.', 
 'Hanoi', 'Leadership training, remote-friendly work, wellness programs', 3200.00, '2025-08-05', 1, 0, 9),

(4, 2, 'UI/UX Designer', 2, 'open', 3, 'Create user-friendly designs and improve customer experience.', 
 'Work with product managers to design wireframes, prototypes, and final UI.', 
 '2+ years experience in Figma, Adobe XD, Sketch.', 
 'Ho Chi Minh City', 'Creative work environment, flexible working hours, free gym membership', 2500.00, '2025-07-15', 1, 0, 16),

(1, 5, 'Cloud Engineer (AWS/GCP)', 1, 'open', 5, 'Design and maintain cloud infrastructure for high-performance applications.', 
 'Implement and manage cloud resources, security policies, and automation scripts.', 
 '4+ years experience with AWS/GCP, Terraform, Kubernetes, and cloud security.', 
 'Da Nang', 'Certification sponsorship, flexible PTO, international career opportunities', 3500.00, '2025-06-28', 2, 0, 17),

(6, 15, 'Blockchain Developer', 5, 'open', 5, 'Develop blockchain-based applications and smart contracts.', 
 'Write and deploy smart contracts, ensure blockchain security, and optimize performance.', 
 '3+ years experience with Solidity, Ethereum, Hyperledger.', 
 'Ho Chi Minh City', 'Remote work, startup culture, equity options', 4000.00, '2025-08-15', 2, 0, 3),

(3, 13, 'System Administrator', 3, 'open', 4, 'Manage IT systems, monitor server performance, and troubleshoot issues.', 
 'Maintain security, configure network infrastructure, and handle cloud backups.', 
 '3+ years experience in Linux/Windows administration, networking, and virtualization.', 
 'Hanoi', 'Paid certifications, work-from-home support, yearly tech allowance', 2700.00, '2025-07-05', 1, 0, 13),

(2, 15, 'Game Developer (Unity)', 1, 'open', 4, 'Develop engaging mobile and PC games using Unity.', 
 'Write game mechanics, implement UI/UX, and optimize performance.', 
 '2+ years experience with Unity, C#, and 3D game development.', 
 'Da Nang', 'Game development workshops, project-based bonuses, free gaming sessions', 2600.00, '2025-07-12', 2, 0, 11),

(5, 11, 'AI Engineer', 1, 'open', 6, 'Design and deploy AI models for predictive analytics and automation.', 
 'Develop deep learning models, work with big data, and fine-tune algorithms.', 
 '5+ years experience in AI, Python, TensorFlow/PyTorch, and NLP.', 
 'Ho Chi Minh City', 'Research funding, flexible work schedule, AI conferences sponsorship', 5000.00, '2025-08-30', 1, 0, 12),
 
 (4, 16, 'Full Stack Developer', 1, 'open', 4, 'Develop and maintain web applications using modern frameworks.', 
 'Build both frontend and backend systems, ensure application security, and optimize performance.', 
 '3+ years experience with JavaScript, React, Node.js, and databases (PostgreSQL/MySQL).', 
 'Hanoi', 'Flexible working hours, remote work options, stock options', 3200.00, '2025-07-25', 2, 0, 1),

(2, 3, 'Cybersecurity Analyst', 1, 'open', 5, 'Analyze and improve system security, monitor potential threats.', 
 'Develop security policies, conduct penetration testing, and ensure data protection.', 
 '4+ years experience in cybersecurity, ethical hacking, and SIEM tools.', 
 'Ho Chi Minh City', 'Cybersecurity training, international conferences, flexible hours', 4500.00, '2025-08-10', 1, 0, 12),

(3, 9, 'Data Scientist', 1, 'open', 5, 'Work on big data analytics, predictive modeling, and AI-driven insights.', 
 'Process large datasets, develop machine learning models, and visualize trends.', 
 '4+ years experience in Python, SQL, TensorFlow, and data visualization tools.', 
 'Da Nang', 'AI research funding, free courses, remote work', 4800.00, '2025-08-20', 1, 0, 14),

(5, 6, 'DevOps Engineer', 1, 'open', 4, 'Develop CI/CD pipelines, monitor infrastructure, and automate deployments.', 
 'Work with developers to improve system reliability and deployment efficiency.', 
 '3+ years experience with Docker, Kubernetes, AWS/GCP, and Terraform.', 
 'Hanoi', 'Work-from-home options, certification sponsorship, annual bonuses', 3800.00, '2025-07-30', 1, 0, 7),

(6, 13, 'Software Architect', 1, 'open', 7, 'Design high-level software architecture for scalable applications.', 
 'Define system architecture, review code, and guide development teams.', 
 '7+ years experience in system design, microservices, and cloud computing.', 
 'Ho Chi Minh City', 'Leadership training, stock options, international travel opportunities', 6500.00, '2025-08-25', 1, 0, 1);


INSERT INTO job_responsibilities (job_id, responsibility) VALUES
(1, 'Design, develop, and maintain web applications using modern front-end and back-end technologies.'),
(1, 'Collaborate with designers, product managers, and other developers to define technical solutions.'),
(1, 'Optimize applications for performance, scalability, and security.'),
(1, 'Mentor junior developers and provide technical guidance.'),
(2, 'Develop and maintain user-facing features using HTML, CSS, and JavaScript.'),
(2, 'Collaborate with UI/UX designers to improve usability.'),
(2, 'Optimize web pages for maximum speed and scalability.'),
(2, 'Work with senior developers to integrate frontend with backend services.'),
(3, 'Build and maintain CI/CD pipelines for automated testing and deployment.'),
(3, 'Monitor system performance and ensure system availability.'),
(3, 'Collaborate with development and IT teams to streamline operations.'),
(3, 'Manage cloud infrastructure and automate server provisioning.'),
(4, 'Develop and implement machine learning models to solve business problems.'),
(4, 'Analyze large datasets to extract actionable insights.'),
(4, 'Collaborate with cross-functional teams to improve data-driven decision making.'),
(4, 'Present findings and recommendations to stakeholders in a clear and concise manner.'),
(5, 'Monitor and analyze security threats to protect company systems and networks.'),
(5, 'Identify vulnerabilities and implement measures to mitigate potential risks.'),
(5, 'Collaborate with IT and development teams to ensure the security of applications and infrastructure.'),
(5, 'Develop and maintain security protocols, policies, and procedures.'),
(6, 'Develop mobile applications using React Native for both iOS and Android platforms.'),
(6, 'Collaborate with product managers, designers, and other developers to build high-quality mobile solutions.'),
(6, 'Ensure the performance, quality, and responsiveness of applications.'),
(6, 'Troubleshoot and debug applications, ensuring a seamless user experience.'),
(7, 'Design and develop automated test scripts for web and mobile applications.'),
(7, 'Collaborate with development teams to ensure quality throughout the SDLC.'),
(7, 'Execute automated tests and analyze test results to identify issues.'),
(7, 'Maintain and enhance the automation framework and test scripts.'),
(8, 'Design and develop scalable and efficient backend services using Node.js.'),
(8, 'Collaborate with front-end developers to integrate user-facing elements with server-side logic.'),
(8, 'Write reusable, testable, and efficient code.'),
(8, 'Ensure high performance and responsiveness to requests from the front-end.'),
(9, 'Facilitate daily stand-ups, sprint planning, sprint retrospectives, and sprint reviews.'),
(9, 'Ensure that the team is following Agile best practices and Scrum processes.'),
(9, 'Assist in removing any obstacles or impediments that the development team faces.'),
(9, 'Work closely with the Product Owner to ensure the product backlog is well-groomed and prioritized.'),
(10, 'Design and create wireframes, prototypes, and user interfaces for web and mobile applications.'),
(10, 'Conduct user research and gather feedback to improve the user experience.'),
(10, 'Collaborate with developers to ensure designs are implemented as intended.'),
(10, 'Stay up to date with the latest design trends and technologies.'),
(11, 'Design, deploy, and manage cloud infrastructure on AWS or GCP.'),
(11, 'Monitor and optimize cloud resources for performance and cost efficiency.'),
(11, 'Implement security best practices and compliance for cloud environments.'),
(11, 'Collaborate with development teams to ensure seamless cloud integration and deployment.'),
(12, 'Design, develop, and deploy blockchain-based applications.'),
(12, 'Collaborate with cross-functional teams to define blockchain project requirements and solutions.'),
(12, 'Write clean, efficient, and secure smart contracts.'),
(12, 'Ensure the scalability, performance, and security of blockchain networks.'),
(13, 'Manage and maintain the company’s IT infrastructure, including servers, networks, and security systems.'),
(13, 'Monitor system performance and troubleshoot issues as they arise.'),
(13, 'Ensure the security of the company’s data and network infrastructure.'),
(13, 'Perform regular system updates, backups, and disaster recovery procedures.'),
(14, 'Design, develop, and maintain engaging and interactive games using Unity.'),
(14, 'Collaborate with designers, artists, and other developers to create high-quality game features.'),
(14, 'Optimize game performance for a smooth experience on multiple platforms.'),
(14, 'Implement and test game mechanics, controls, and physics to ensure a high-quality user experience.'),
(15, 'Design, develop, and deploy machine learning models and AI solutions.'),
(15, 'Collaborate with cross-functional teams to integrate AI models into production environments.'),
(15, 'Optimize AI algorithms for efficiency, scalability, and performance.'),
(15, 'Stay up to date with the latest AI research and technologies to continuously improve models.'),
(16, 'Design, develop, and maintain both front-end and back-end components of web applications.'),
(16, 'Collaborate with cross-functional teams to define and deliver technical solutions.'),
(16, 'Write clean, maintainable, and efficient code for both client-side and server-side logic.'),
(16, 'Ensure the application is optimized for maximum speed and scalability.'),
(17, 'Monitor and defend against security threats to protect the company’s network and data.'),
(17, 'Conduct vulnerability assessments and penetration testing on systems and applications.'),
(17, 'Develop and implement security policies, procedures, and protocols.'),
(17, 'Respond to security breaches and incidents, and ensure proper documentation and reporting.'),
(18, 'Collect, clean, and analyze large datasets to extract valuable insights.'),
(18, 'Build and implement machine learning models and algorithms.'),
(18, 'Develop and maintain data pipelines to support data-driven decision making.'),
(18, 'Collaborate with cross-functional teams to define and implement data strategies.'),
(19, 'Design, implement, and manage CI/CD pipelines for automated deployments.'),
(19, 'Monitor and optimize infrastructure for performance, scalability, and security.'),
(19, 'Collaborate with developers to ensure seamless integration and delivery processes.'),
(19, 'Automate infrastructure provisioning and configuration management.'),
(20, 'Design and oversee the architecture of complex software systems.'),
(20, 'Lead the development team to ensure that the design aligns with business requirements.'),
(20, 'Create and enforce software development standards and best practices.'),
(20, 'Review and optimize code and architecture for performance, scalability, and maintainability.');

INSERT INTO job_requirements (job_id, requirement) VALUES
(1, '5+ years of experience as a Full Stack Developer.'),
(1, 'Proficient in JavaScript (React, Angular, or Vue) for front-end development.'),
(1, 'Strong experience with Node.js, Python, Ruby on Rails, or Java for back-end development.'),
(1, 'Experience with RESTful APIs, GraphQL, and microservices architecture.'),
(1, 'Familiarity with Docker, Kubernetes, and cloud platforms (AWS, GCP, or Azure).'),
(1, 'Strong knowledge of CI/CD pipelines and DevOps practices.'),
(2, '1+ year of experience in frontend development or relevant internship experience.'),
(2, 'Good knowledge of HTML, CSS, and JavaScript.'),
(2, 'Familiarity with at least one JavaScript framework (e.g., React, Vue, Angular).'),
(2, 'Basic understanding of responsive design and cross-browser compatibility.'),
(2, 'Knowledge of version control systems like Git.'),
(2, 'Strong willingness to learn and grow in a fast-paced environment.'),
(3, '3+ years of experience in DevOps or system administration roles.'),
(3, 'Proficient with CI/CD tools such as Jenkins, GitLab CI, or GitHub Actions.'),
(3, 'Experience with cloud platforms (AWS, Azure, or GCP).'),
(3, 'Strong knowledge of Docker and Kubernetes.'),
(3, 'Familiarity with scripting languages like Bash or Python.'),
(3, 'Understanding of monitoring tools like Prometheus, Grafana, or ELK stack.'),
(4, '3+ years of experience in data science or related field.'),
(4, 'Strong proficiency in Python and data science libraries (Pandas, NumPy, scikit-learn, TensorFlow).'),
(4, 'Experience with SQL and NoSQL databases.'),
(4, 'Familiarity with data visualization tools like Matplotlib, Seaborn, or Tableau.'),
(4, 'Understanding of machine learning algorithms and statistical modeling.'),
(4, 'Ability to communicate technical concepts to non-technical stakeholders.'),
(5, '3+ years of experience in cybersecurity or information security.'),
(5, 'Strong knowledge of network security, firewalls, and encryption technologies.'),
(5, 'Experience with security tools like IDS/IPS, SIEM, and vulnerability scanners.'),
(5, 'Familiarity with regulatory requirements and standards such as GDPR, HIPAA, or ISO 27001.'),
(5, 'Proficiency in security auditing and incident response procedures.'),
(5, 'Ability to work independently and as part of a team in high-pressure environments.'),
(6, '2+ years of experience in mobile app development with React Native.'),
(6, 'Proficiency in JavaScript, React, and Redux.'),
(6, 'Strong understanding of mobile UI/UX design principles.'),
(6, 'Experience with RESTful APIs and third-party libraries.'),
(6, 'Familiarity with version control systems such as Git.'),
(6, 'Ability to write clean, maintainable code and documentation.'),
(7, '2+ years of experience in software testing and automation.'),
(7, 'Proficiency in test automation tools such as Selenium, Cypress, or Appium.'),
(7, 'Strong programming skills in Java, Python, or JavaScript.'),
(7, 'Good understanding of SDLC, Agile methodologies, and CI/CD pipelines.'),
(7, 'Experience in writing and executing test cases, bug reporting, and issue tracking.'),
(7, 'Knowledge of databases and API testing.'),
(8, '3+ years of experience in backend development with Node.js.'),
(8, 'Strong knowledge of JavaScript (ES6+) and Node.js frameworks like Express or Koa.'),
(8, 'Experience with databases like MongoDB, PostgreSQL, or MySQL.'),
(8, 'Knowledge of RESTful API design and development.'),
(8, 'Experience with version control tools such as Git.'),
(8, 'Familiarity with cloud services (AWS, Azure, GCP) and containerization (Docker).'),
(9, '3+ years of experience as a Scrum Master or Agile Coach.'),
(9, 'Strong knowledge of Scrum and Agile methodologies.'),
(9, 'Experience in facilitating Scrum ceremonies such as daily stand-ups, sprint reviews, and retrospectives.'),
(9, 'Excellent communication, facilitation, and conflict resolution skills.'),
(9, 'Experience working with cross-functional teams in an Agile environment.'),
(9, 'Scrum Master certification (CSM, PSM, or equivalent) is preferred.'),
(10, '2+ years of experience as a UI/UX Designer or similar role.'),
(10, 'Proficiency in design tools such as Figma, Adobe XD, Sketch, or similar.'),
(10, 'Strong understanding of user-centered design principles and methods.'),
(10, 'Experience in wireframing, prototyping, and interaction design.'),
(10, 'Ability to work collaboratively with developers and other stakeholders.'),
(10, 'Excellent communication skills to present design ideas and solutions.'),
(11, '3+ years of experience as a Cloud Engineer or similar role.'),
(11, 'Proficiency in AWS or GCP services such as EC2, S3, Lambda, etc.'),
(11, 'Strong knowledge of cloud security, networking, and storage solutions.'),
(11, 'Experience with infrastructure as code tools like Terraform or CloudFormation.'),
(11, 'Familiarity with CI/CD pipelines and cloud automation tools.'),
(11, 'Strong problem-solving skills and ability to work independently.'),
(12, 'Proven experience in blockchain development (Ethereum, Hyperledger, etc.).'),
(12, 'Proficiency in programming languages like Solidity, Go, or JavaScript.'),
(12, 'Experience with smart contracts and decentralized applications (DApps).'),
(12, 'Strong understanding of cryptography and blockchain protocols.'),
(12, 'Familiarity with consensus algorithms, security, and scalability solutions.'),
(12, 'Knowledge of version control systems (Git) and CI/CD pipelines.'),
(13, 'Proven experience as a System Administrator or similar role.'),
(13, 'Strong knowledge of Linux/Unix and Windows operating systems.'),
(13, 'Experience with networking protocols, firewalls, and VPNs.'),
(13, 'Familiarity with cloud computing platforms (AWS, Azure, GCP).'),
(13, 'Proficiency in scripting and automation tools (Bash, PowerShell, etc.).'),
(13, 'Good understanding of system monitoring tools and practices.'),
(14, 'Proven experience as a Game Developer, with a strong portfolio of Unity projects.'),
(14, 'Proficiency in C# and Unity development environment.'),
(14, 'Strong knowledge of game mechanics, artificial intelligence, and physics engines.'),
(14, 'Experience with version control tools such as Git.'),
(14, 'Familiarity with 3D modeling and animation tools (e.g., Blender, Maya) is a plus.'),
(14, 'Ability to work in a fast-paced, collaborative, and Agile environment.'),
(15, 'Strong experience in AI/ML technologies, including deep learning and natural language processing.'),
(15, 'Proficiency in programming languages like Python, TensorFlow, and PyTorch.'),
(15, 'Experience with data preprocessing, feature engineering, and model evaluation techniques.'),
(15, 'Knowledge of cloud platforms (AWS, GCP, or Azure) for deploying AI solutions.'),
(15, 'Experience with version control systems like Git.'),
(15, 'Strong analytical and problem-solving skills with the ability to work independently.'),
(16, 'Proficiency in front-end technologies such as HTML, CSS, JavaScript, and modern JavaScript frameworks like React, Angular, or Vue.'),
(16, 'Experience with back-end technologies such as Node.js, Python, Ruby on Rails, or Java.'),
(16, 'Strong understanding of databases, including relational and NoSQL databases like PostgreSQL, MySQL, or MongoDB.'),
(16, 'Experience with RESTful APIs, GraphQL, and microservices architecture.'),
(16, 'Knowledge of version control systems like Git.'),
(16, 'Strong problem-solving skills and the ability to work independently and in teams.'),
(17, 'Strong knowledge of network security protocols and systems.'),
(17, 'Experience with firewalls, intrusion detection systems, and encryption methods.'),
(17, 'Proficient in security tools such as SIEM, IDS/IPS, and anti-malware solutions.'),
(17, 'Experience in performing risk assessments and security audits.'),
(17, 'Knowledge of regulatory compliance standards (e.g., GDPR, HIPAA, PCI DSS).'),
(17, 'Strong problem-solving skills and ability to stay up-to-date with emerging threats and vulnerabilities.'),
(18, 'Strong knowledge of statistical analysis and machine learning algorithms.'),
(18, 'Experience with programming languages such as Python, R, or SQL.'),
(18, 'Familiarity with data visualization tools such as Tableau or Power BI.'),
(18, 'Experience with big data technologies like Hadoop or Spark.'),
(18, 'Strong problem-solving skills and the ability to interpret complex data.'),
(18, 'Experience with cloud platforms (AWS, GCP, or Azure) for data processing.'),
(19, 'Strong experience with automation tools like Jenkins, Docker, or Kubernetes.'),
(19, 'Proficiency in scripting languages like Bash, Python, or Ruby.'),
(19, 'Experience with cloud platforms such as AWS, GCP, or Azure.'),
(19, 'Strong understanding of infrastructure as code (IaC) principles and tools like Terraform or CloudFormation.'),
(19, 'Familiarity with monitoring tools like Prometheus, Grafana, or ELK stack.'),
(19, 'Good knowledge of version control systems such as Git.'),
(20, '10+ years of experience in software development and system architecture.'),
(20, 'Proficiency in multiple programming languages like Java, C#, or Python.'),
(20, 'Strong knowledge of software design patterns, microservices, and cloud architectures.'),
(20, 'Experience with enterprise-level application design and deployment.'),
(20, 'Proven track record in designing scalable and maintainable software solutions.'),
(20, 'Excellent leadership skills with the ability to mentor and guide technical teams.');

INSERT INTO job_benefits (job_id, benefit) VALUES
(1, 'Competitive salary based on experience.'),
(1, 'Flexible working hours (remote or hybrid options).'),
(1, 'Learning and development opportunities.'),
(2, 'Supportive and friendly team environment.'),
(2, 'Opportunities to learn modern technologies.'),
(2, 'Flexible working hours and remote work options.'),
(3, 'Competitive salary and annual performance bonus.'),
(3, 'Professional training and certification support.'),
(3, 'Health insurance and wellness programs.'),
(4, 'Competitive salary and performance bonuses.'),
(4, 'Opportunities for career growth and skill development.'),
(4, 'Health insurance, including dental and vision coverage.'),
(5, 'Competitive salary and bonus structure.'),
(5, 'Comprehensive health insurance, including dental and vision coverage.'),
(5, 'Access to professional development resources and certifications.'),
(6, 'Flexible work hours and the possibility of remote work.'),
(6, 'Competitive salary with performance-based bonuses.'),
(6, 'Opportunities for skill development and career advancement.'),
(7, 'Flexible working hours and the possibility of remote work.'),
(7, 'Competitive salary and performance bonuses.'),
(7, 'Opportunities for career growth, training, and certifications.'),
(8, 'Opportunity to work in an innovative and collaborative environment.'),
(8, 'Competitive salary and performance-based bonuses.'),
(8, 'Health insurance and other employee benefits.'),
(9, 'Competitive salary and career advancement opportunities.'),
(9, 'Flexible working hours and remote work options.'),
(9, 'Health insurance and wellness programs.'),
(10, 'Creative and dynamic work environment.'),
(10, 'Opportunity to work on innovative and impactful projects.'),
(10, 'Flexible working hours and remote work options.'),
(11, 'Competitive salary and performance-based incentives.'),
(11, 'Work with cutting-edge cloud technologies and innovative projects.'),
(11, 'Flexible working hours and remote work options.'),
(12, 'Competitive salary with performance-based bonuses.'),
(12, 'Work with cutting-edge blockchain technology and participate in innovative projects.'),
(12, 'Flexible working hours and remote work options.'),
(13, 'Competitive salary and benefits package.'),
(13, 'Opportunities for career development and certifications.'),
(13, 'Flexible working hours with remote work options.'),
(14, 'Competitive salary and performance bonuses.'),
(14, 'Opportunities for professional growth and skill development.'),
(14, 'Access to cutting-edge gaming technologies and tools.'),
(15, 'Competitive salary with performance-based incentives.'),
(15, 'Access to cutting-edge AI tools and technologies.'),
(15, 'Opportunities for career growth and development in a rapidly growing field.'),
(16, 'Competitive salary and performance bonuses.'),
(16, 'Flexible working hours with remote working options.'),
(16, 'Professional development and growth opportunities.'),
(17, 'Competitive salary with bonus opportunities based on performance.'),
(17, 'Comprehensive health insurance and wellness programs.'),
(17, 'Flexible work hours and remote work options.'),
(18, 'Competitive salary with opportunities for career growth.'),
(18, 'Health insurance and wellness programs for employees.'),
(18, 'Access to learning and development resources to enhance your skills.'),
(19, 'Competitive salary with performance-based bonuses.'),
(19, 'Flexible working hours and remote working options.'),
(19, 'Comprehensive health insurance and wellness programs.'),
(20, 'Highly competitive salary and performance bonuses.'),
(20, 'Opportunity to work on cutting-edge technology and innovative projects.'),
(20, 'Flexible work arrangements including remote work options and flexible hours.');



